# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    passing-values-bw-steps:
    
        name: Upload Artifact
        runs-on: ubuntu-latest
        steps:
            - name: set value using env vars
              run: |
                echo "variablename=this is value" >> $GITHUB_ENV

            - name : create-variables
              id: var_source_step
              run: |
                echo "performing random task"
                echo "::set-output name=var1_name::techschool"
                echo "::set-output name=var2_date::$(date +'%Y-%m-%d-%H-%M')"
            - name: get-variable-value
              run: |
                echo "printing values"
                echo variablename: ${{ env.variablename}}
                echo var1_name: ${{ steps.var_source_step.outputs.var1_name }}
                echo var2_date: ${{ steps.var_source_step.outputs.var2-date }}

              


        


        
 
